SELECT COUNT(1)
FROM
    PPR.TN08_PAYMENTS PAY1
    JOIN PPR.TN09_PAYMENT_ALLOCATIONS PAY2 ON PAY1.CN08_ID = PAY2.CN08_ID
    JOIN TAC.TT18_PAYMENT_INSTRUCTIONS TAC2 ON TAC2.CT18_SLIP_ID = PAY1.CN08_INTA_SLIP_ID AND TAC2.CT18_PAYMENT_ID = PAY1.CN08_INTA_PAYMENT_ID
WHERE
    TAC2.CSTD_STATUS = 'Unmatched'
;


SELECT COUNT(CN08_ID), CN06_INSTRUMENT_CODE
FROM
    (
        SELECT DISTINCT PAY1.CN08_ID, PAY1.CN06_INSTRUMENT_CODE
        FROM
            PPR.TN08_PAYMENTS PAY1
            JOIN PPR.TN09_PAYMENT_ALLOCATIONS PAY2 ON PAY1.CN08_ID = PAY2.CN08_ID
        WHERE
            -- PAY1.CR01_INTERNAL_ID != '999999999999999999'
            -- AND PAY2.CR01_INTERNAL_ID != '999999999999999999'
            -- AND EXISTS ( -- FOR CHECKING THE EXISTENCE OF CONNECTION
            -- AND
            NOT EXISTS ( -- FOR CHECKING THE NOT EXISTENCE OF CONNECTION (PROBABLY THE BUG)
                SELECT 1
                FROM
                    TAC.TT01_TRANSACTIONS TAC1
                WHERE
                    TAC1.CT01_ENTITY_ID = PAY1.CN08_ID
                    AND TAC1.CSTD_ENTITY = 'PAY'
            )
            -- AND NOT EXISTS (
            --      SELECT 1
            --      FROM
            --              TAC.TT18_PAYMENT_INSTRUCTIONS TAC2
            --      WHERE
            --              TAC2.CT18_SLIP_ID = PAY1.CN08_INTA_SLIP_ID
            --              AND TAC2.CT18_PAYMENT_ID = PAY1.CN08_INTA_PAYMENT_ID
            -- )
            AND PAY1.CSTD_PMT_STATUS = 'PAY_DPST'
    )
GROUP BY CN06_INSTRUMENT_CODE
ORDER BY CN06_INSTRUMENT_CODE;