SELECT
	REG0.TIN,
	REG0.INTERNAL_ID,
	LETAN.CC03_ID AN,
	LETCOMP.CC03_ID COMPLIAMNCE,
	SUBSTR(LETAN.CC03_ENTITY_ID, 1, INSTR(LETAN.CC03_ENTITY_ID, '-') - 1) RETURN_ID
FROM
	REG.TAXPAYER REG0
	JOIN STL.TC03_LETTER LETCOMP ON
		LETCOMP.CC01_ID = 135
		AND REG0.INTERNAL_ID = LETCOMP.CR01_INTERNAL_ID
		AND LETCOMP.CC03_ID = (
			SELECT MAX(SUBLETCOMP.CC03_ID)
			FROM STL.TC03_LETTER SUBLETCOMP
			WHERE
				SUBLETCOMP.CC01_ID = 135
				AND REG0.INTERNAL_ID = SUBLETCOMP.CR01_INTERNAL_ID
		)
	JOIN STL.TC03_LETTER LETAN ON
		LETAN.CC03_ID = LETCOMP.CC03_ENTITY_ID
		AND REG0.INTERNAL_ID = LETAN.CR01_INTERNAL_ID
		AND LETAN.CC01_ID IN ('52','54','55','56','57','58','59','104', '137')
		AND LETAN.CC03_ID = (
			SELECT MAX(SUBLETAN.CC03_ID)
			FROM STL.TC03_LETTER SUBLETAN
			WHERE
				REG0.INTERNAL_ID = SUBLETAN.CR01_INTERNAL_ID
				AND SUBLETAN.CC01_ID IN ('52','54','55','56','57','58','59','104', '137')
		)
WHERE
	EXISTS (
		SELECT 1
	    FROM RET.TA02_RETURNS RET0
    	WHERE
    		RET0.CA02_RETURN_ID = SUBSTR(LETAN.CC03_ENTITY_ID, 1, INSTR(LETAN.CC03_ENTITY_ID, '-') - 1)
    		AND RET0.CA02_RETURN_VERSION = SUBSTR(LETAN.CC03_ENTITY_ID, INSTR(LETAN.CC03_ENTITY_ID, '-') + 1,  LENGTH(LETAN.CC03_ENTITY_ID))
			AND RET0.CA02_TAX_DUE IS NOT NULL
    		AND RET0.CA02_TAX_DUE > 0
    		AND RET0.CR01_INTERNAL_ID = REG0.INTERNAL_ID
	)
	AND (
		SELECT MAX(RET0.CA02_RETURN_VERSION)
	    FROM RET.TA02_RETURNS RET0
    	WHERE
    		RET0.CA02_RETURN_ID = SUBSTR(LETAN.CC03_ENTITY_ID, 1, INSTR(LETAN.CC03_ENTITY_ID, '-') - 1)
    		AND RET0.CR01_INTERNAL_ID = REG0.INTERNAL_ID
	) = SUBSTR(LETAN.CC03_ENTITY_ID, INSTR(LETAN.CC03_ENTITY_ID, '-') + 1,  LENGTH(LETAN.CC03_ENTITY_ID))
	AND NOT EXISTS (
		SELECT DISTINCT OBJ2.CA02_RETURN_ID
    	FROM
	    	OBJ.TO01_REQUESTS OBJ1
	    	JOIN OBJ.TO02_REQUEST_DETAILS OBJ2 ON OBJ1.CO01_REQUEST_NO = OBJ2.CO01_REQUEST_NO
    	WHERE
	    	OBJ1.CSTD_REQUEST_STATUS = 'OBJ_OPEN'
	    	AND OBJ2.CA02_RETURN_ID = SUBSTR(LETAN.CC03_ENTITY_ID, 1, INSTR(LETAN.CC03_ENTITY_ID, '-') - 1)
	)
	AND (
		SELECT COUNT(DISTINCT RET0.CA02_TAX_DUE)
	    FROM RET.TA02_RETURNS RET0
    	WHERE
				RET0.CA02_RETURN_ID = SUBSTR(LETAN.CC03_ENTITY_ID, 1, INSTR(LETAN.CC03_ENTITY_ID, '-') - 1)
				AND RET0.CA02_TAX_DUE IS NOT NULL
				AND RET0.CA02_TAX_DUE > 0
	) > 1
	AND TIN IN (
		'0889788499'
	)
