SELECT
	RET2.CSTD_RETURN_TYPE                                                     F0,
	RET2.CA02_TAX_YEAR                                                        F1,
	TO_CHAR(SYSDATE, 'yyyy/mm/dd', 'NLS_CALENDAR=Persian')                    F2,
	REG1.CR01_TIN_ID                                                          F3,
	REG13.CR13_TRADE_NAME                                                     F4,
	REG4.CR04_NATIONAL_ID                                                     F5,
	GETGTOFROMOFFICEID(REG16.CS04_ID)                                         F6,
	ADM4.CS04_NAME                                                            F7,
	ADM4.CS04_PHONE                                                           F8,
	ADM4.CS04_POSTAL_ADR                                                      F9,
	REG20.CR20_POSTAL_ADDRESS                                                 F10,
	REG11.CR11_FIRST_NAME                                                     F11,
	REG11.CR11_SECOND_NAME                                                    F12,
	RET2.CA02_RETURN_ID                                                       F13,
	RET2.CA02_RETURN_VERSION                                                  F14,
	TO_CHAR(RET2.CA02_TAX_PERIOD_TO, 'yyyy/mm/dd', 'NLS_CALENDAR=Persian')    F15,
	TO_CHAR(RET2.CA02_TAX_PERIOD_FROM, 'yyyy/mm/dd', 'NLS_CALENDAR=Persian')  F16,
	REG1.CR01_NATURAL_PER_FLAG                                                F17,
	REG10.CR10_REG_NUMBER                                                     F18,
	REG13.CR13_NAME                                                           F19,
	REG6.CSTD_ACTIVITY_CODE                                                   F20,
	REG25.CR25_FIXED_PHONE                                                    F21,
	RET3.CA03_RETURN_CONTENT                                                  F22
FROM
	RET.TA02_RETURNS RET2
	LEFT JOIN RET.TA03_RET_CONTENT RET3 ON RET3.CA02_RETURN_ID = RET2.CA02_RETURN_ID AND RET3.CA02_RETURN_VERSION = RET2.CA02_RETURN_VERSION
	LEFT JOIN REG.TR01_TAXPAYER REG1 ON REG1.CR01_INTERNAL_ID = RET2.CR01_INTERNAL_ID
	LEFT JOIN REG.TR04_NATURAL_PERSON REG4 ON REG1.CR04_NATURAL_PER_ID IS NOT NULL AND REG1.CR04_NATURAL_PER_ID = REG4.CR04_NATURAL_PER_ID
	LEFT JOIN REG.TR06_BRANCH_BUSI_ACTIVITY REG6 ON RET2.CR01_INTERNAL_ID = REG6.CR01_INTERNAL_ID AND RET2.CR03_BRANCH_CODE = REG6.CR03_BRANCH_CODE AND REG6.CR06_END_DATE IS NULL
	LEFT JOIN REG.TR10_LEGAL_PERSON REG10 ON REG1.CR10_LEGAL_PER_ID IS NOT NULL AND REG1.CR10_LEGAL_PER_ID = REG10.CR10_LEGAL_PER_ID
	LEFT JOIN REG.TR11_NATURAL_PER_NAME REG11 ON REG1.CR04_NATURAL_PER_ID = REG11.CR04_NATURAL_PER_ID AND REG11.CR11_END_DATE IS NULL
	LEFT JOIN REG.TR13_LEGAL_PER_NAME REG13 ON REG1.CR10_LEGAL_PER_ID = REG13.CR10_LEGAL_PER_ID AND REG13.CR13_END_DATE IS NULL
	LEFT JOIN REG.TR16_TAXPAYER_OFFICE REG16 ON REG1.CR01_INTERNAL_ID = REG16.CR01_INTERNAL_ID AND REG16.CR16_END_DATE IS NULL
	LEFT JOIN REG.TR17_BRANCH_NAME REG17 ON REG17.CR17_END_DATE IS NULL AND REG17.CR01_INTERNAL_ID = RET2.CR01_INTERNAL_ID AND RET2.CR03_BRANCH_CODE = REG17.CR03_BRANCH_CODE
  LEFT JOIN REG.TR19_BRANCH_PHYSICAL_ADDR REG19 ON RET2.CR01_INTERNAL_ID = REG19.CR01_INTERNAL_ID AND RET2.CR03_BRANCH_CODE = REG19.CR03_BRANCH_CODE AND REG19.CR19_END_DATE IS NULL
  LEFT JOIN REG.TR20_BRANCH_POSTAL_ADDR REG20 ON RET2.CR01_INTERNAL_ID = REG20.CR01_INTERNAL_ID AND RET2.CR03_BRANCH_CODE = REG20.CR03_BRANCH_CODE AND REG20.CR20_END_DATE IS NULL
	LEFT JOIN REG.TR25_OFFICIALS REG25 ON RET2.CR01_INTERNAL_ID = REG25.CR01_INTERNAL_ID AND RET2.CR03_BRANCH_CODE = REG25.CR03_BRANCH_CODE
	LEFT JOIN ADM.TS04_OFFICE ADM4 ON ADM4.CS04_ID = REG16.CS04_ID
WHERE
	RET2.CA02_RETURN_ID = '1469816'
	AND RET2.CA02_RETURN_VERSION = 2
