SELECT
	AVAILABLE_AMT,
	CODE_DESC
FROM
	(
		SELECT
			CT01_DESC AS CODE_DESC,
			AMOUNT AS AVAILABLE_AMT
		FROM
			(
				SELECT
					MAX( CT01_DESC ) CT01_DESC,
					SUM( AMOUNT ) AMOUNT
				FROM
					(
						SELECT
							TT01.CT01_DESC,
							CASE
								WHEN TT01.CSTD_DC = 'DT' THEN 0 - TT01.CT01_AMOUNT
								ELSE TT01.CT01_AMOUNT
							END AMOUNT
						FROM
							TT01_TRANSACTIONS TT01,
							TAX_RETURNS TA02
						WHERE
							TT01.CT01_VALUE_DATE <= SYSDATE
							AND TT01.CT01_REVERSED_FLAG = 'N'
							AND TT01.CT01_CLEARED_FLAG = 'Y'
							AND TT01.CT01_FINALIZED_FLAG = 'Y'
							AND TT01.CSTD_LIABILITY_TYPE = 'INTRES'
							AND TT01.CSTD_TRAN_TYPE IN(
								SELECT
									INTERNAL_CODE
								FROM
									STD_CODES
								WHERE
									GROUP_CODE = 'TRANSACTION_TYPE'
									AND PARENT_INTERNAL_CODE IN(
										'TA',
										'PA',
										'RL'
									)
							)
							AND TT01.CR01_INTERNAL_ID = TA02.CR01_INTERNAL_ID
							AND TT01.CR03_BRANCH_CODE = TA02.CR03_BRANCH_CODE
							AND TT01.CSTD_TAX_TYPE = TA02.CA09_TAX_TYPE_CODE
							AND TT01.CT01_TAX_YEAR = TA02.CA02_TAX_YEAR
							AND TT01.CT01_PERIOD = TA02.CA02_TAX_PERIOD
							AND TA02.CA02_RETURN_ID = #return_id:String#
							AND TA02.CA02_RETURN_VERSION = #return_version:String#
					UNION ALL SELECT
							TT01.CT01_DESC,
							CASE
								WHEN TT01.CSTD_DC = 'DT' THEN 0 - TT01.CT01_AMOUNT
								ELSE TT01.CT01_AMOUNT
							END AMOUNT
						FROM
							TT01_TRANSACTIONS TT01
						WHERE
							TT01.CT01_VALUE_DATE <= SYSDATE
							AND TT01.CT01_REVERSED_FLAG = 'N'
							AND TT01.CT01_CLEARED_FLAG = 'Y'
							AND TT01.CT01_FINALIZED_FLAG = 'Y'
							AND TT01.CSTD_LIABILITY_TYPE = 'INTRES'
							AND TT01.CSTD_TRAN_TYPE IN(
								SELECT
									INTERNAL_CODE
								FROM
									STD_CODES
								WHERE
									GROUP_CODE = 'TRANSACTION_TYPE'
									AND PARENT_INTERNAL_CODE IN(
										'TA',
										'PA',
										'RL'
									)
							)
							AND TT01.CSTD_ALLOCATED_ENTITY = 'RET'
							AND TT01.CT01_ALLOCATED_ENTITYID = #return_id:String#
					) TAB1
				GROUP BY
					CT01_DESC
			) TAB
		WHERE
			TAB.AMOUNT > 0
	) AVAILABLE
