CREATE
  OR REPLACE VIEW REG.TAXPAYER_INFO_FOR_SIMPLE(
    TIN,
    TAXPAYERCATEGORY,
    INTERNALID,
    FIRSTNAME,
    SENCONDNAME,
    THIRDNAME,
    LASTNAME,
    FATHERNAME,
    BIRTHDAY,
    GENDER,
    NAME,
    TRADENAME,
    LEGALTYPE,
    TAXPAYERTYPE,
    STATUS,
    RISKSCORE,
    TAXOFFICE,
    SECURITYLEVEL,
    NATIONAL_ID,
    REG_NUMBER,
    PHYSICAL_ADDRESS,
    TURNOVER,
    TAXPAYER_SIZE,
    LEGAL_PER_ID,
    TITLE,
    NATURAL_PER_ID
  ) AS SELECT
    a.CR01_TIN_ID TIN,
    a.CR01_NATURAL_PER_FLAG TAXPAYERCATEGORY,
    a.CR01_INTERNAL_ID INTERNALID,
    TO_CHAR( b.CR11_FIRST_NAME ) FIRSTNAME,
    TO_CHAR( b.CR11_SECOND_NAME ) SENCONDNAME,
    TO_CHAR( b.CR11_THIRD_NAME ) THIRDNAME,
    TO_CHAR( b.CR11_LAST_NAME ) LASTNAME,
    TO_CHAR( c.CR04_FATHER_NAME ) FATHERNAME,
    c.CR04_BIRTH_DATE BIRTHDAY,
    c.CSTD_GENDER GENDER,
    TO_CHAR( DECODE( a.CR01_NATURAL_PER_FLAG, 'Y', b.CR11_FIRST_NAME || ' ' || b.CR11_LAST_NAME, 'N', d.CR13_NAME )) AS NAME,
    TO_CHAR( d.CR13_TRADE_NAME ) TRADENAME,
    m.CSTD_LEGAL_ENTITY_TYPE LEGALTYPE,
    f.CSTD_TAXPAYER_TYPE TAXPAYERTYPE,
    a.CSTD_TAXPAYER_STATUS STATUS,
    a.CR01_RISK_SCORE RISKSCORE,
    e.CS04_ID TAXOFFICE,
    a.CSTD_SECURITY_LEVEL_ID SECURITYLEVEL,
    TO_CHAR( c.CR04_NATIONAL_ID ) NATIONAL_ID,
    TO_CHAR( g.CR10_REG_NUMBER ) REG_NUMBER,
    TO_CHAR( i.CR19_PHYSICAL_ADDRESS ) PHYSICAL_ADDRESS,
    a.CR01_TURNOVER TURNOVER,
    a.CSTD_TAXPAYER_SIZE TAXPAYER_SIZE,
    a.CR10_LEGAL_PER_ID LEGAL_PER_ID,
    c.CSTD_TITLE TITLE,
    a.CR04_NATURAL_PER_ID NATURAL_PER_ID
  FROM
    TR01_TAXPAYER a
  LEFT JOIN TR11_NATURAL_PER_NAME b ON
    a.CR04_NATURAL_PER_ID = b.CR04_NATURAL_PER_ID
    AND(
      b.CR11_START_DATE IS NULL
      OR b.CR11_START_DATE < SYSDATE
    )
    AND(
      b.CR11_END_DATE IS NULL
      OR b.CR11_END_DATE > SYSDATE
    )
  LEFT JOIN TR04_NATURAL_PERSON c ON
    a.CR04_NATURAL_PER_ID = c.CR04_NATURAL_PER_ID
  LEFT JOIN TR10_LEGAL_PERSON g ON
    a.CR10_LEGAL_PER_ID = g.CR10_LEGAL_PER_ID
  LEFT JOIN TR13_LEGAL_PER_NAME d ON
    a.CR10_LEGAL_PER_ID = d.CR10_LEGAL_PER_ID
    AND(
      d.CR13_START_DATE IS NULL
      OR d.CR13_START_DATE < SYSDATE
    )
    AND(
      d.CR13_END_DATE IS NULL
      OR d.CR13_END_DATE > SYSDATE
    )
  LEFT JOIN TR24_LEGAL_PERSON_TYPE m ON
    a.CR10_LEGAL_PER_ID = m.CR10_LEGAL_PER_ID
    AND(
      m.CR24_START_DATE IS NULL
      OR m.CR24_START_DATE < SYSDATE
    )
    AND(
      m.CR24_end_DATE IS NULL
      OR m.CR24_end_DATE > SYSDATE
    )
  JOIN TR14_TAXPAYER_ACTIVE_TYPE f ON
    a.CR01_INTERNAL_ID = f.CR01_INTERNAL_ID
    AND(
      f.CR14_START_DATE IS NULL
      OR f.CR14_START_DATE < SYSDATE
    )
    AND(
      f.CR14_END_DATE IS NULL
      OR f.CR14_END_DATE > SYSDATE
    )
  JOIN TR16_TAXPAYER_OFFICE e ON
    a.CR01_INTERNAL_ID = e.CR01_INTERNAL_ID
    AND(
      e.CR16_START_DATE IS NULL
      OR e.CR16_START_DATE < SYSDATE
    )
    AND(
      e.CR16_END_DATE IS NULL
      OR e.CR16_END_DATE > SYSDATE
    )
  LEFT JOIN TR19_BRANCH_PHYSICAL_ADDR i ON
    a.CR01_INTERNAL_ID = i.CR01_INTERNAL_ID
    AND i.CR03_BRANCH_CODE = '000'
    AND(
      i.CR19_START_DATE IS NULL
      OR i.CR19_START_DATE < SYSDATE
    )
    AND(
      i.CR19_END_DATE IS NULL
      OR i.CR19_END_DATE > SYSDATE
    )
