SELECT DISTINCT 
  TXP0.CR01_TIN_ID, 
  TXP0.CR01_INTERNAL_ID, 
  TXP0.CR01_NATURAL_PER_FLAG IS_NATURAL_PERSON,
  (
    SELECT COUNT(DISTINCT SUBTXP0.CR03_BRANCH_CODE)
    FROM REG.TR07_BRANCH_TAX_TYPE_REG SUBTXP0
    WHERE 
      TXP0.CR01_INTERNAL_ID = SUBTXP0.CR01_INTERNAL_ID
      AND SUBTXP0.CR07_EXPIRY_DATE IS NULL
      AND SUBTXP0.CSTD_TAX_TYPE = 'WST'
  ) NUM_BRANCH,
  CASE WHEN (
    EXISTS (
      SELECT 1
      FROM RET.TA02_RETURNS SUBRET0
      WHERE 
        SUBRET0.CA02_TAX_YEAR = '1395'
        AND SUBRET0.CSTD_RETURN_TYPE = 'FRM32'
        AND SUBRET0.CR01_INTERNAL_ID = TXP0.CR01_INTERNAL_ID
    )
  ) THEN 'YES' ELSE 'NO' END HAS_FRM32_1395,
  CASE WHEN (
    EXISTS (
      SELECT 1 
      FROM 
        AUD.TU09_AUDIT_RETURN SUBAUD0
        JOIN RET.TA02_RETURNS SUBRET0 ON SUBRET0.CA02_RETURN_ID = SUBAUD0.CU05_ID
      WHERE
        SUBRET0.CA02_TAX_YEAR = '1395'
        AND SUBRET0.CSTD_RETURN_TYPE = 'FRM32'
        AND SUBRET0.CR01_INTERNAL_ID = TXP0.CR01_INTERNAL_ID
    )
  ) THEN 'YES' ELSE 'NO' END IS_IN_AUDIT
FROM 
  ADM.TS04_OFFICE AOF1
  JOIN REG.TR16_TAXPAYER_OFFICE TXP1 ON TXP1.CS04_ID = AOF1.CS04_ID
  JOIN REG.TR01_TAXPAYER TXP0 ON TXP0.CR01_INTERNAL_ID = TXP1.CR01_INTERNAL_ID
  JOIN REG.TR07_BRANCH_TAX_TYPE_REG TXP2 ON TXP0.CR01_INTERNAL_ID = TXP2.CR01_INTERNAL_ID
WHERE 
  AOF1.CSTD_OFFICE_TYPE = 'TO'   
  AND SUBSTR(REGEXP_SUBSTR(AOF1.CS04_NAME, '[0-9]+', 1), 0, 2) = '32'
  AND TXP2.CSTD_TAX_TYPE = 'WST'
  AND TXP1.CR16_END_DATE IS NULL
  AND TXP0.CSTD_TAXPAYER_STATUS = 'TXP_ACTI'
  AND TXP2.CR07_EXPIRY_DATE IS NULL
;