SELECT TXP0.CR01_INTERNAL_ID, COUNT(DISTINCT RET0.CA02_TAX_PERIOD)
FROM 
    RET.TA02_RETURNS RET0
    JOIN REG.TR01_TAXPAYER TXP0 ON RET0.CR01_INTERNAL_ID = TXP0.CR01_INTERNAL_ID
WHERE
    RET0.CA02_TAX_YEAR = '1395'
    AND RET0.CSTD_FILING_CHANNEL = 'RETPTL'
    AND RET0.CSTD_RETURN_TYPE = 'FRM32'
    AND RET0.CSTD_STATUS = 'RET_PSTD'
    AND RET0.CA09_TAX_TYPE_CODE = 'WST'
    AND RET0.CSTD_RETURN_SOURCE = 'TXP'
GROUP BY TXP0.CR01_INTERNAL_ID
HAVING COUNT(DISTINCT RET0.CA02_TAX_PERIOD) = 12
ORDER BY TXP0.CR01_INTERNAL_ID
;